SuperTest/SuperTest.Web/Models/ErrorViewModel.cs
using System;

namespace SuperTest.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperTest/SuperTest.Web/Models/Usuarios/CadastrarUsuarioModel.cs
using System.ComponentModel.DataAnnotations;

namespace SuperTest.Web.Models.Usuarios
{
    public class CadastrarUsuarioModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nome é obrigatório")]
        public string Nome { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email é obrigatório")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "CPF é obrigatório")]
        public string CPF { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Senha é obrigatória")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
        public bool UsuarioCadastrado { get; set; }
    }
}

SuperTest/SuperTest.Web/Models/Usuarios/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace SuperTest.Web.Models.Usuarios
{
    public class LoginModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email é obrigatório")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Senha é obrigatória")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
    }
}

SuperTest/SuperTest.Web/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using SuperTest.Domain.Commands.Usuarios;
using SuperTest.Domain.Services;
using SuperTest.Web.Models.Usuarios;

namespace SuperTest.Web.Controllers
{
    public class AccountController : BaseController
    {
        private readonly IUsuarioService _usuarioService;

        public AccountController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        [HttpPost]
        public IActionResult Login(LoginModel model)
        {

            if (ModelState.IsValid)
            {
                var command = new AutenticarUsuarioCommand(model.Email, model.Senha);
                bool ehValido = _usuarioService.AutenticarUsuario(command);

                if(!ehValido)
                {
                    foreach(var notification in _usuarioService.Notifications)
                    {
                        //TODO: Apresentar notificaçoes
                    }
                }
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CadastrarUsuario(CadastrarUsuarioModel model)
        {
            if(ModelState.IsValid)
            {
                var command = new CadastrarNovoUsuarioCommand(model.Nome, model.Email, model.CPF, model.Senha);
                _usuarioService.CadastrarUsuario(command);

                if(_usuarioService.HasNotification)
                {
                    foreach (var notification in _usuarioService.Notifications)
                    {
                        //TODO: Apresentar notificaçoes
                    }

                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

SuperTest/SuperTest.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperTest.Web.Controllers
{
    public class BaseController : Controller
    {

    }
}

SuperTest/SuperTest.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SuperTest.Domain.Services;
using SuperTest.Web.Models;
using SuperTest.Web.Models.Usuarios;

namespace SuperTest.Web.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IUsuarioService _usuarioService;

        public HomeController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperTest/SuperTest.Web/ViewComponents/CadastroUsuarioViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperTest.Web.Models.Usuarios;

namespace SuperTest.Web.ViewComponents
{
    public class CadastroUsuarioViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            CadastrarUsuarioModel model = new CadastrarUsuarioModel();

            return View(model);
        }
    }
}

SuperTest/SuperTest.Web/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperTest.Web.Models.Usuarios;

namespace SuperTest.Web.ViewComponents
{
    public class LoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            LoginModel model = new LoginModel();

            return View(model);
        }
    }
}

SuperTest/SuperTest.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@await Component.InvokeAsync("CadastroUsuario")

SuperTest/SuperTest.Web/Views/Shared/Components/CadastroUsuario/Default.cshtml
@model CadastrarUsuarioModel

<div class="row">
    <div class="col-md-7">
        <br /><br />
        <div class="text-center mt-5 mb-2">
            <h1 class="display-1">
                <span class="font-weight-bold">SUPER </span><span class="font-weight-light bg-success text-white">TESTE</span>
            </h1>
            <p class="pt-2">
                <img src="~/images/award.svg" width="120" alt="logo garantia" />
            </p>
        </div>
    </div>
    <div class="col-md-5 mx-auto">
        <div class="card">
            <div class="card-header">
                <div class="text-center">
                    <h3><span id="become">Become </span><span class="font-weight-bold">SUPER</span><span class="font-weight-light">TESTER</span></h3>
                </div>
            </div>
            <div class="card-body">
                <form asp-controller="Account" asp-action="CadastrarUsuario" method="post">
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-with-icon">
                                <input asp-for="Nome" class="form-control mb-2" placeholder="Nome">
                                <i class="fas fa-file-signature"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-with-icon">
                                <input asp-for="Email" class="form-control mb-2" placeholder="Email">
                                <i class="fas fa-envelope"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-with-icon">
                                <input asp-for="CPF" class="form-control mb-2" placeholder="CPF">
                                <i class="fas fa-id-card"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="input-with-icon">
                                <input asp-for="Senha" class="form-control mb-2" placeholder="Senha">
                                <i class="fas fa-lock"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <button class="btn btn-dark btn-block btn-lg">
                                <span class="font-weight-bold">CRIAR</span><span class="font-weight-light">CONTRA</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

SuperTest/SuperTest.Web/Views/Shared/Components/Login/Default.cshtml
@model LoginModel

<form class="form-inline" asp-controller="Account" asp-action="Login" method="post">
    <div class="form-group">
        <div class="form-group">
            <div class="input-with-icon">
                <input asp-for="Email" class="form-control mr-2" placeholder="Email">
                <i class="fas fa-envelope"></i>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group pt-4">
            <div class="input-with-icon">
                <input asp-for="Senha" class="form-control mr-2" placeholder="Senha">
                <i class="fas fa-lock"></i>
                <span asp-validation-for="Senha" class="text-danger"></span>
                <small id="passwordHelpBlock" class="form-text text-muted">
                    <a href="#" data-toggle="modal" data-target="#modalPassword">Esqueceu a senha?</a>
                </small>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-dark"><span class="font-weight-light">ENTRAR</span></button>
</form>

SuperTest/SuperTest.Web/Views/Shared/_Layout.cshtml
@model LoginModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Super Teste</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link rel="stylesheet" href="~/css/sketchy.bootstrap.css" />*@
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
              integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
              crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img id="logo" class="d-inline-block mr-1" alt="Logo" src="~/images/logo.png" width="50px">
                    <span class="text-center"><br><span class="font-weight-bold">SUPER</span><span class="font-weight-light">TESTE</span></span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @await Component.InvokeAsync("Login")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div id="modalPassword" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Forgot password</h3>
                        <button type="button" class="close font-weight-light" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <div class="modal-body">
                        <p>Reset your password..</p>
                    </div>
                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                        <button class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>


    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2019 - SuperTest.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>